### ISSUE TITLE
troubleshooting keychain password issues

### ISSUE THREAD

**Issue by dannypaz** [electron/electron-notarize#10]
I receive errors saying `item not found in keychain` when the item exists and settings have been changed to allow any application to view them.

Line in question:
```const password = `@keychain:"Application Loader: ${appleId}"\`;```

Is there anything I need to know RE: setup for keychain other than the steps outlined in the readme? Using an env for password works fine, but would like to use keychain instead

Mac: 10.14.6
Node: 12

**Comment by hatton** [comment]
I have the same problem.  It works find to run altool in a terminal:

`xcrun altool --notarize-app -f "<my app file>" --primary-bundle-id "<my app id>" 
-u "<my apple id>" -p "@keychain:altoolpw"
`

But 
``
notarize({
 ...
appleIdPassword: "@keychain:altoolpw"
})
``
Gives:
``Error: The keychain item 'altoolpw' was not found.``

**Comment by dbkr** [comment]
One small thing that could be added is that altool has an option for storing the keychain password:

```
xcrun altool --store-password-in-keychain-item something -u '<your apple id>' -p apassword
```
This makes sure the keychain item is added exactly how altool wants it to be added.

Protip: If you put a dummy password in on the command line, you can then open Keychain Access, search for the entry and update the password with the real password, then you don't have to worry about expunging the password from your shell history.

**Comment by simonheys** [comment]
I got this to work for now by duplicating my existing Application Loader keychain entry and adding quotes `"` around the name. So instead of the name being 

`Application Loader: ${appleId}` 

it is

`"Application Loader: ${appleId}"`

**Comment by mathielo** [comment]
I had a similar problem: the CI (Jenkins) could never find the item in the keychain. 

I was able to solve it [with this answer](https://stackoverflow.com/a/56396125/2752041). I was missing one simple step: **Always allow** `altool` to read the password in the host Mac. 

So pretty much I logged into the Mac that would run the command, ran it in the terminal there first and selected "Always allow" when asked for the keychain password. After that the CI was able to access the password in the keychain! :tada:

**Comment by IgorVNC** [comment]
Even allowing the item to all apps do not solve the issue, still getting at Jenkins side:

`*** Error: The keychain item 'AC_PASSWORD' was not found. Failed to get the password for the keychain item 'AC_PASSWORD'.`

The only one thig left to try is to add the password item to System keychain (not Login)

`$ sudo security add-generic-password -a uuu -s sss -w ppp -A /Library/Keychains/System.keychain`

**Comment by IgorVNC** [comment]
Yeah, adding to System.keychain solved my Jenkins issue
