### ISSUE TITLE
It takes a long time?

### ISSUE THREAD

**Issue by tnrich** [electron/electron-notarize#11]
Hey there, I'm just wondering if it is expected that notarization takes such a long time?

I have the following in by electron-builder config: 

```
    "afterSign": "src/misc/notarize.js",
    "mac": {
      "hardenedRuntime": true,
      "gatekeeperAssess": false,
      "entitlements": "src/misc/entitlements.mac.plist",
      "entitlementsInherit": "src/misc/entitlements.mac.plist"
    },
```

And
```
//notarize.js
const { notarize } = require('electron-notarize');

exports.default = async function notarizing(context) {
  const { electronPlatformName, appOutDir } = context;  
  if (electronPlatformName !== 'darwin') {
    return;
  }

  const appName = context.packager.appInfo.productFilename;

  return await notarize({
    appBundleId: 'com.teselagen.openVectorEditor',
    appPath: `${appOutDir}/${appName}.app`,
    appleId: process.env.APPLEID,
    appleIdPassword: process.env.APPLEIDPASS,
  });
};
```

The notarize function seems to take a really long time, like several minutes. Do you know where that delay is mostly coming from? Do I need to run it every time I make a new release?

Other than the slowness it works great!
Thanks!

**Comment by tnrich** [comment]
As a followup, I'm wondering.. Is it necessary to wait for notarization before continuing with the subsequent steps of building the apps? Maybe the app could be built simultaneously to the notarization process? 

I'm not really sure how notarization works so maybe this makes no sense. It would just be nice to not have to wait the couple extra minutes to publish a new release. Thanks!

**Comment by shiqi** [comment]
the wait is for hearing back from apple about the notarization request and then stapling the ticket back to the app that you notarized so users can still open it without Internet (if your app support offline mode) https://developer.apple.com/documentation/xcode/notarizing_your_app_before_distribution/customizing_the_notarization_workflow#3087720

would be nice to expose an option in the pkg to skip the stapling though

HTH

**Comment by tnrich** [comment]
Thanks @shiqi that makes sense. I'll want to wait for it to be stapled so I guess I'll just have to wait it out. 

Thanks!

**Comment by portah** [comment]
I'm not quite sure is it related or not. I followed instructions in this post https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/. And finally it goes without errors (auth one) but for now it is almost 30min and it still notarizing. Is there a way for more verbose output?

**Comment by shiqi** [comment]
you could run `xcrun altool --notarization-history 0 -u <USER_NAME> (--asc-provider <PROVIDER>)  -p ` to get history of your requests, it seems apple is either rate limiting or having serious back log on notarization requests at the moment, I have several requests marked as `in progress` in that list and the longest one waited for more than 6 hours (of course the build job timed out for that one)

**Comment by AMoreaux** [comment]
Currently notary service is down. Thanks Apple! 🙁
https://developer.apple.com/system-status/
![image](https://user-images.githubusercontent.com/7237157/66549286-408f9a80-eb43-11e9-98ed-a501cdc7b8cd.png)

**Comment by simon300000** [comment]
Oh no, that's why my CI takes 5 hours and still not finished...

**Comment by benatkin** [comment]
This issue can probably be closed, if there's nothing electron-notarize can do about it. It can still be found by searching if it's closed.
