### ISSUE TITLE
slower response from apple API server for UUID status

### ISSUE THREAD

**Issue by shiqi** [electron/electron-notarize#12]
this is not a problem of this pkg but kinda need a solution because I am not sure if/when apple will improve this on their end. (or maybe I need to switch ISP lol)

I've been observing a lot of errors about 
electron-notarize:spawn cmd xcrun terminated with code: 239
Error Packaging App: Error: Failed to check status of notarization request: XXXXX
altool[5307:3097828] *** Error: Apple Services operation failed. Could not find the RequestUUID.
in our ci runs

the app is still notarized correctly (I am getting all the emails about notarization completed and approved)

seems apple API server is responding way slower now (for us, at least) than before and 10 seconds wait we set within the notarization pkg is not enough anymore. I am guessing their server is taking a lot heavier load than before now that Catalina is GA-ed and they might have scaling problem.

**Comment by roberttolton** [comment]
Maybe this is related, but I'm unable to notarize my app both locally and through Travis:

```
Error: Failed to find request UUID in output:
2019-10-15 01:33:30.386 altool[3735:9496] *** Error: Unable to validate your application. We are unable to create an authentication session.
```

**Comment by kimmsassss** [comment]
[5307:3097828] ***
