### ISSUE TITLE
Support "early staple"

### ISSUE THREAD

**Issue by stigi** [electron/electron-notarize#17]
Often times `stapler staple` succeeds before the notarization backend returns a successful notarization status.

The notarization plugin for Fastlane supports this "feature" by calling it *early staple* (see here https://github.com/zeplin/fastlane-plugin-notarize/blob/master/lib/fastlane/plugin/notarize/actions/notarize_action.rb#L9)

What it does is essentially just checking wether `xcrun stapler staple ...` succeeds while polling for the notarization result.

**Comment by MarshallOfSound** [comment]
This seems like it violates apples rules about undue load on the stapling / notarization service.  Currently we meet their guidelines, I don't want to deviate
