### ISSUE TITLE
app_specific_password

### ISSUE THREAD

**Issue by Ivorfason** [electron/electron-notarize#23]
with the following commandLine:
`security add-generic-password -a "AC_USERNAME" -w <app_specific_password> -s "AC_PASSWORD"`
how can I get the correct <app_specific_password>?

I have tried the actually appleIdPassword, but it still got error: 
`altool[42480:474497] *** Error: The keychain item 'AC_PASSWORD' was not found. Failed to get the password for the keychain item 'AC_PASSWORD'.`

**Comment by erikaperugachi** [comment]
read the README
