### ISSUE TITLE
Add a license file ?

### ISSUE THREAD

**Issue by ihbar** [electron/electron-notarize#32]
Would it be possible to include a license file ? It will help to clarify the copyright applicable to the module. (I assume the copyright will be in the MIT license file)
Thank you.

**Comment by bsivanov** [comment]
Yes, it's super important to add LICENSE file [because](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license):
> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by bsivanov** [comment]
I can see that the [npm package](https://www.npmjs.com/package/electron-notarize) itself is under MIT, but it would be good to have this here as well - this will give me the opportunity to give property attribution - e.g. I am currently not sure if the copyright should be to GitHub or Samuel Attard (@MarshallOfSound).

**Comment by ihbar** [comment]
Thanks a lot
