### ISSUE TITLE
App upload intermittently fails

### ISSUE THREAD

**Issue by Hexxeh** [electron/electron-notarize#33]
Periodically I see that uploading the app to Apple fails with this error:

```
2020-01-23T12:42:46.700Z electron-notarize zip succeeded, attempting to upload to Apple
/Volumes/macbuilder7/workspace/app/node_modules/electron-notarize/lib/index.js:4
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
Error: Failed to upload app to Apple's notarization servers

2020-01-23 04:42:46.941 altool[28355:10218559] *** Error: Server returned an invalid MIME type: text/plain, body: Unauthenticated
```

Often, 2-3 concurrent builds will fail in the same way. Restarting them typically makes them pass. It seems the later calls within the notarization process are retried upon failure, and I see this same error successfully recovered from there. Could/should the same logic be applied to the upload step too?

**Comment by mifi** [comment]
For me it crashes half of the time when building. would be nice with some retry

**Comment by malept** [comment]
Retry is not happening, see https://github.com/electron/electron-notarize/pull/37#issuecomment-621958283

**Comment by mifi** [comment]
Can we keep the issue open? It’s still an issue even though retry has not been accepted as a solution.

**Comment by malept** [comment]
It's still a problem, but it's really a problem on Apple's end. Trying to fix it on our end will be problematic because the behavior of their tools and servers aren't particularly transparent and could change at any time.
