### ISSUE TITLE
Failed notorize: Unrecognized selector sent to instance

### ISSUE THREAD

**Issue by KASOGIT** [electron/electron-notarize#42]
Hi,

since month i'm notorizing my app with success but since today the process fail with this error:
![image](https://user-images.githubusercontent.com/15908751/81225454-8df4bd00-8fe9-11ea-8d5b-6ff8ca976f0b.png)

Do you have any idea of what wrong happening ?

**Comment by MarshallOfSound** [comment]
Looks like your Xcode installation is broken? Try updating / reinstalling xcode
