### ISSUE TITLE
Travis-CI: xcrun: error: unable to find utility "altool", not a developer tool or in PATH

### ISSUE THREAD

**Issue by adgrace** [electron/electron-notarize#5]
Hi,
I have applied your instructions from https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/ to our existing CICD pipeline and get the following error:
Error: Failed to upload app to Apples notarization servers
xcrun: error: unable to find utility "altool", not a developer tool or in PATH

Any thoughts much appreciated

**Comment by malept** [comment]
_Caveat: I'm not a macOS developer, I'm only speculating based on the limited amount of information._

My guess is that your `osx_image` is not new enough. What is the value of that config in `.travis.yml`?

**Comment by nocodaio** [comment]
I had to manually select the current Xcode installation (maybe as I had a different Xcode version installed at some time). However I got the same error message as you and the below step resolved it.

```
sudo xcode-select -s /Applications/Xcode.app
```

**Comment by snicol21** [comment]
@adgrace I'm not a MacOS developer either, but I overcame this same error. I was able to overcome this by installing Xcode through the App Store.

![image](https://user-images.githubusercontent.com/15724638/59628601-44b02c00-90fe-11e9-9c04-55badb919ff3.png)

Not sure if this would fix yours, but it worked for me.

**Comment by myaisv** [comment]
I solved this issue by running
`sudo xcode-select -r`

**Comment by JackWCollins** [comment]
I had an existing, old XCode installed. Updated to the newest version, but it still didn't work until I ran `sudo xcode-select -r` per @myaisv. Thank you!

**Comment by malept** [comment]
There are multiple answers to the original question and to subsequent questions, so I'm closing this.

**Comment by davidmurdoch** [comment]
I've tried both `sudo xcode-select -s /Applications/Xcode.app` and `sudo xcode-select -r` on Travis's xcode11.3 on Mac OS 10.13.6 and still receive the `unable to find utility "altool", not a developer tool or in PATH` error.

Build output here: https://travis-ci.org/github/trufflesuite/ganache/jobs/663721352#L3824

Implementation here: https://github.com/trufflesuite/ganache/blob/efdabb22feabff10f594447a842dd13dd8f14491/afterSignHook.js#L25-L34

Anyone have any thoughts on what could be wrong with my config?

**Comment by davidmurdoch** [comment]
My issue was that my travis config wasn't actually using the root-level `osx_image` directive of "xcode11.3"; this directive was being ignored due to my use of Travis' `include` matrix. The correct way to specify the `osx_image` when using an `include` matrix is as follows:

```
matrix:
  include:
  - os: osx
    osx_image: "xcode11.3"
  - os: linux
    dist: bionic
```

Once I made this change I didn't need to try the `xcode-select` solutions above.

**Comment by TongDaDa** [comment]
The "altool" command doesn't exist In the $PATH in some version of system. and then we need to add it to the symbolic file. Ensure the "/usr/local/bin" path is in the $PATH variable.

ln -s /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Versions/A/Support/altool /usr/local/bin/altool

**Comment by janakg** [comment]
`altool` is not part of the Command Line Tools. 

Create a symbolic link or add this to the path. 

Xcode 12
`/Applications/Xcode.app/Contents/Developer/usr/bin`
