### ISSUE TITLE
 electron 10  and electron 9 is not sign ok

### ISSUE THREAD

**Issue by hiair2323** [electron/electron-notarize#51]
**"electron": "^8.3.0",is ok  but electron": "10.1.1  and electron 9 is not sign ok"    i am use github actions**
• packaging       platform=darwin arch=x64 electron=10.1.1 appOutDir=dist_electron/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v10.1.1/electron-v10.1.1-darwin-x64.zip size=76 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v10.1.1/electron-v10.1.1-darwin-x64.zip duration=1.803s
  • signing         file=dist_electron/mac/xxx.app identityName=Developer ID Application: xxxxx) identityHash=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx provisioningProfile=none
 ERROR  Error: Command failed: codesign --sign 6885E750C2C5A4A86E5BC8599EA9CD3480F090A5 --force --keychain /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/95c4640e40a2a514e44b980605b0da40349af7a09b25d9f202864baad16279fc.keychain --options runtime --entitlements build/entitlements.mac.plist /Users/runner/work/yanbaoke-khd/yanbaoke-khd/dist_electron/mac/xxx.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/runner/work/yanbaoke-khd/yanbaoke-khd/dist_electron/mac/xxx.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/runner/work/yanbaoke-khd/yanbaoke-khd/dist_electron/mac/xxx.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
       
Error: Command failed: codesign --sign 6885E750C2C5A4A86E5BC8599EA9CD3480F090A5 --force --keychain /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/95c4640e40a2a514e44b980605b0da40349af7a09b25d9f202864baad16279fc.keychain --options runtime --entitlements build/entitlements.mac.plist /Users/runner/work/yanbaoke-khd/yanbaoke-khd/dist_electron/mac/xxx.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/runner/work/yanbaoke-khd/yanbaoke-khd/dist_electron/mac/xxx.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/runner/work/yanbaoke-khd/yanbaoke-khd/dist_electron/mac/xxx.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Pipe._handle.close (net.js:607:12)
From previous event:
    at module.exports.execFileAsync (/Users/runner/work/yanbaoke-khd/yanbaoke-khd/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/electron-osx-sign/util.js:41:10)
    at /Users/runner/work/yanbaoke-khd/yanbaoke-khd/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/electron-osx-sign/sign.js:172:17
From previous event:
    at signApplicationAsync (/Users/runner/work/yanbaoke-khd/yanbaoke-khd/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/electron-osx-sign/sign.js:127:6)
    at /Users/runner/work/yanbaoke-khd/yanbaoke-khd/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/electron-osx-sign/sign.js:338:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yanbaoke@2.9.3 electron:build-yun: `npm install && vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yanbaoke@2.9.3 electron:build-yun script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/runner/.npm/_logs/2020-09-02T03_37_30_036Z-debug.log
##[error]Process completed with exit code 1.

**Comment by fp07** [comment]
Any update on this?

**Comment by megancooper** [comment]
@hiair2323 were you able to solve this issue? I'm experiencing the same thing
