### ISSUE TITLE
Notarize task started failing today

### ISSUE THREAD

**Issue by lini** [electron/electron-notarize#58]
Using electron-notarize to submit an electron 8.x app. Everything worked fine until today. Now the notarize task fails with different errors:

```
RangeError: Invalid string length
or
An error occurred saving your changes to the Apple database
```

Note that the notarization still runs and finishes - I receive a mail from Apple that the app was notarized successfully. However, the electron build process fails long before that. Using Xcode 12.1 and macOS 10.15.7 and electron-notarize@1.0.0

**Comment by arantes555** [comment]
Having the same problem. Seems kinda widespread : https://developer.apple.com/forums/thread/664888

**Comment by lini** [comment]
Yes, it turned out Apple servers had problems but they did not even update their status page. Builds are working again.
