### ISSUE TITLE
Signed electron app does not start with iohook on OSX (Unhandled Errpr: no suitable image found)

### ISSUE THREAD

**Issue by hemanth500apps** [electron/electron-notarize#66]
I have a signed and notarized App where I want to use iohook to simulate key taps. I had no problems building iohook locally but when I run it through the CI, where I sign and notarize the app, the app throws the following error upon starting:
![Screenshot-2021-03-17-at-4-38-51-PM](https://user-images.githubusercontent.com/49899639/111577938-2a2a4b80-87d9-11eb-9802-1af5f958eb0e.png)

**Comment by MarshallOfSound** [comment]
You need to have your native modules in `app.asar.unpacked` not in the `app.asar` otherwise they are not codesigned during package
