### ISSUE TITLE
Incorrect error log

### ISSUE THREAD

**Issue by Nes-si** [electron/electron-notarize#68]
Hi there.
I've got an error during notarization (You must first sign the relevant contracts online). But that's not the point. The terminal output log is incorrect. First it outputs an error info ("⨯ Failed to upload app to Apple's notarization servers", ...) then it duplicates it with 11480 spaces indent! See:
![error](https://user-images.githubusercontent.com/5188972/114955423-5a5f1b80-9e65-11eb-89f8-11bed3aabf9e.png)
This is huge and non-readable piece of text. It can freeze a terminal application.
[log notarizing.txt](https://github.com/electron/electron-notarize/files/6321746/log.notarizing.txt)

**Comment by MarshallOfSound** [comment]
This log comes straight out of apples notarytool
