### ISSUE TITLE
More verbose debug messages?

### ISSUE THREAD

**Issue by sergek** [electron/electron-notarize#9]
Hi, I'm running the build and notarization routine of a mac electron app on a Go CI and not long ago it has started failing the notarization step (it worked previously)

The only debug message I get is 

```
Error: Failed to upload app to Apples notarization servers

2019-07-22 14:37:30.213 go-agent[23269:316324] *** Error: Unable to validate your application. The application you have selected does not exist.

    at /go-agent-01/pipelines/app/node_modules/electron-notarize/src/index.ts:76:13
```
At the moment I'm not sure if it's some electron-notarize problem or go-agent problem.
Maybe more verbose error messages would help here?
What do you guys think?

**Comment by sergek** [comment]
Sorry, apparently this was some problem with apple id account.
But my question remains - is possible to display more verbose errors? Something beside Error: Failed to upload app to Apples notarization servers
Thanks!

**Comment by grahamtallen** [comment]
I agree, it would be great if there was an option to configure electron-notarize to use the --verbose flag when notarizing

**Comment by mikeyyyzhao** [comment]
@sergek I'm running into the same bug as you above, what was the issue with your apple id account? I checked my contracts through https://appstoreconnect.apple.com/agreements/#/ and they're all signed. The only thing I don't have done is set up "Set Up Tax, Banking, and Contacts" but since we're not making a paid app, this shouldn't matter right? I have the forms signed for paid apps, just not the tax and banking section.

**Comment by mikeyyyzhao** [comment]
I think there's a delay between signing the contracts and being able to notarize it. I ran the exact same command  a while later without changing a thing in our code and I was able to notarize the app.

**Comment by sqpdln** [comment]
one thing you can do is add ```process.env.DEBUG = 'electron-notarize'``` before ```
const { notarize } = require('electron-notarize')```

**Comment by MarshallOfSound** [comment]
A lot of these error messages come from notarytool / altool.  More information is normally sent to you in an email, we have no control over this as it's all apples tooling we just shell out to
