### ISSUE TITLE
Can't get notarytool option working

### ISSUE THREAD

**Issue by aguynamedben** [electron/electron-notarize#92]
If anybody's gotten notarytool working with electron-notarize please let me know. I'm happy to fix bugs or add documentation, but I can't figure out how to get notarytool to work with any of the available methods.

## Legacy (altool) + password works
```js
return notarize({
  tool: 'legacy',
  appPath,
  appBundleId: 'io.hypertools.Command-E',
  appleId,
  appleIdPassword,
}).catch((error) => {
  console.error(`configs/notarize.js: Notarization failed : ${error.message}`);
  process.exit(2);
});
```

## notarytool + password doesn't work
```js
// TODO: doesn't work
return notarize({
  tool: 'notarytool',
  appPath,
  appleId,
  appleIdPassword,
  teamId,
}).catch((error) => {
  console.error(`configs/notarize.js: Notarization failed : ${error.message}`);
  process.exit(2);
});
```
Fails with this error:
```
Error: HTTP status code: 401. Invalid credentials. Username or password is incorrect. Use the app-specific password generated at appleid.apple.com. Ensure that all authentication arguments are correct.
```
I'm using the exact same values for `appleId` and `appleIdPassword` that I pass when using legacy (`altool`), these calls are in the same script and those variable have the same values.

## notarytool + keychain + keychainProfile doesn't work

```js
return notarize({
  tool: 'notarytool',
  appPath,
  // TODO: Fix these values
  // https://github.com/electron/electron-notarize/issues/88
  // * `keychain` shouldn't be required
  // * `keychainProfile` should work but just doesn't
  keychain: '/Users/standefer/Library/Keychains/login.keychain-db',
  keychainProfile: 'AC_PASSWORD',
}).catch((error) => {
  console.error(`configs/notarize.js: Notarization failed : ${error.message}`);
  process.exit(2);
});

```

Fails with this error:
```
Error: No Keychain password item found for profile: AC_PASSWORD

Run 'notarytool store-credentials' to create another credential profile.
```
I've tried the debug command `security list-keychains` to list all my keychains. I've tried other keychain values. I've tried modifying electron-notarize myself to omit the --keychain argument, but I've run into various issues.

Has anybody figured out how to get notifytool working? Even hints would be helpful... I'm willing to try out different combinations and make improvements to electron-notarize if anybody has any clues. But I'm stumped! If you've gotten it working please paste your notarize script in here! 🙏 

More discussion in here: https://github.com/electron/electron-notarize/issues/88 At first I thought this was just an issue with the --keychain argument, but upon further investigation it seems something might be broken with how electron-notarize calls notarytool in general.

**Comment by jwatte** [comment]
It looks like notarytool stored the AC_PASSWORD item in the iCloud keychain.
I can't find a way to pass in a keychain name that maps to "iCloud keychain" though -- "iCloud" is not it.
The docs claim that "--keychain" is not needed if iCloud is used.

**Comment by astoilkov** [comment]
@aguynamedben I figured out why "notarytool + password" doesn't work. It doesn't work with `@keychain:name`, you should directly put the password which isn't a very good idea. The only option that's left is to wait for the merge of #94.

**Comment by astoilkov** [comment]
@groundwater Actually, did you find a viable solution for this?

**Comment by astoilkov** [comment]
@aguynamedben Actually, did you find a viable solution for this?

**Comment by MarshallOfSound** [comment]
Closed by #94

**Comment by sunknudsen** [comment]
Hey @MarshallOfSound,

Ran `xcrun notarytool store-credentials test` to store credentials in Keychain using API key created using https://appstoreconnect.apple.com/access/api (“Developer” access).

Somehow, following throws “Error: No Keychain password item found for profile: test”. Ideas?

```javascript
await electronNotarize.notarize({
  appPath: appPath,
  keychain: `${homedir()}/Library/Keychains/login.keychain-db`,
  keychainProfile: "test",
  tool: "notarytool",
})
```

**Comment by sunknudsen** [comment]
I also tried with “App Manager” access… same issue.

**Comment by sunknudsen** [comment]
Using `appleApiKey`, `appleApiKeyId` and `appleApiIssuer` worked… so looks like an issue related to Keychain.

Has any of you been able to use `keychain` and  `keychainProfile`?

**Comment by jthrilly** [comment]
I tried today and experienced the same issue as you ("No keychain password item found for profile").

**Comment by sunknudsen** [comment]
Hey @MarshallOfSound, was excited about https://github.com/electron/notarize/pull/94.

Heads-up, updated to [1.2.4](https://www.npmjs.com/package/@electron/notarize/v/1.2.4) but issue is still present.

Anyone using  [@electron/notarize](https://www.npmjs.com/package/@electron/notarize) with `keychain` and `keychainProfile` without running into this issue?
